services:
  db:
    image: postgres:16
    container_name: pg_grocery_db
    env_file: .env
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./init:/init
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_grocery_db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
